# +------------+-----------------------------------------------------+
# | Chip Type  | Available Labels                                    |
# +------------+-----------------------------------------------------+
# | IMECII_2   | 5--A_corner, 5--E_corner, E--1_corner,              |
# |            | B-Left, C-Left, D-Left, E-Left,                     |
# |            | A-Right, B-Right, C-Right, D-Right, E-Right,        |
# |            | 2-Top, 3-Top, 4-Top, 5-Top,                         |
# |            | 1-Bottom, 2-Bottom, 3-Bottom, 4-Bottom, 5-Bottom    |
# +------------+-----------------------------------------------------+
# | IMECII_3   | 1A, 1B, 1C, 1D, 1E, 1F, 1G, 1H, 1I,                 |
# |            | 2A, 2B, 2C, 2D, 2E, 2F, 2G, 2H, 2I,                 |
# |            | 3A, 3B, 3C, 3D, 3E, 3F, 3G, 3H, 3I,                 |
# +------------+-----------------------------------------------------+
# | IMECII_4   | 1A, 1B, 1C,                                         | 
# |            | 2A, 2B, 2C,                                         |
# |            | 3A, 3B, 3C,                                         |
# |            | 4A, 4B, 4C,                                         |
# |            | 5A, 5B, 5C                                          |
# +------------+-----------------------------------------------------+

# Example configuration entry:
# 
#    chip_type = "IMECII_2"  # Specifies the type of chip being used
# 
#    # Define features and their locations, copy and paste as required
#    [[features]]
#    label = "D-Left" # Label as it appears in the table above
#    feature_location = [88, 850] # [x, y] coordinates
# 
#    [[features]]
#    label = "E-Left"
#    feature_location = [85, 124]
# 
#    ...


chip_type = "IMECII_4"

[[features]]
label = "1C"
feature_location = [2320, 2700]

[[features]]
label = "2A"
feature_location = [568, 2340]
